apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: continumm
resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - loki-configmap.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-service.yaml
